### ISSUE TITLE
switch branches

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [archenroot/gentoo-overlay#12]
Tell me when I can rename `master` branch in `old` and the `repoman` branch in `master`

**Comment by archenroot** [comment]
I am also working on multiple new ebuilds, master branch should stay the latest, so you when you work on your branch, you can always pull changes from repoman back to master.

Or explain me why do you like to rename branches, maybe I don't get the point here...

**Comment by Alessandro-Barbieri** [comment]
Nvm, it was faster but I can pull request. The only issue is that I removed 2 or 3 broken ebuilds

**Comment by archenroot** [comment]
I see :-). What ebuilds have you actually removed, I didn't check whole pull request? better next time to mention in commit message: removing non working ebuild of media-libs/somelib...

**Comment by Alessandro-Barbieri** [comment]
I removed the folder `dev-java/ibm-jdk-bin/`
