### ISSUE TITLE
matlab 2017a license

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [archenroot/gentoo-overlay#18]
If you have the EULA text, can you put it in `licenses/MATLAB-EULA`?

**Comment by archenroot** [comment]
I am not yet sure if I will leave this ebuild here. Actually the installation media consists of 2 DVD media which you need to use in a way:
- mount DVD 1 and start install
- in the middle of installation process you are asked for replace DVD 1 with DVD 2 
- you can continue

I don't know how to manage replace ISO mounted file during ebuild execution... if you know any hints for this scenario I am hearing you

**Comment by LGTrader** [comment]
I run Matlab 2017a (Home Use license) on Gentoo. No need for DVDs. If you are a licensed user just download all the installation files through the update center and install. Activate the license and you're good to go. No EULA required. I have Matlab talking to archenroot/tensorflow through Python. Seems to work fine.

**Comment by archenroot** [comment]
I also run Matlab 2017a on Gentoo, but via manual install :-) The idea was to have Gentoo ebuild for Matlab. Or do you have some ebuild (different) you use?

But thanks for the hint with install files via site and not using DVD, it will be than easier to manage the ebuild.

Regarding TensorFlow I noticed suddenly that the ebuild is not stable, will need to investigate....

**Comment by LGTrader** [comment]
No ebuild here for Matlab. I download the install files from Mathworks by hand (which you could require in your ebuild as a standard by-hand prefetch) and just run them as root. My license is single-user so in the Matlab install I give my Gentoo user name and it's good to go. As there are no explicit dependencies, and remembering that Gentoo is not a supported distro, there are a few minor things that I've had to work around but I don't think an ebuild is likely to fix those.

As for tensorflow I probably should learn to write an ebuild and then give you better feedback. 0.5.0 says it depends on >=dev-util/bazel-0.1.0, while 0.6.0 and 9999 says >=sys-devel/bazel-0.1.1. I see that 0.5.0 will apparently install (I haven't done it but portage didn't complain) but neither 0.6.0 or 9999 will. Makes me wonder if Gentoo devs moved bezel, you coded for that move in 0.6.0 and 9999, and now maybe they've moved it back?

**Comment by archenroot** [comment]
Matlab - this is more long term goal to maintain Matlab for Gentoo

TensorFlow - it is very messy and I need to clean that up :-) you are
welcomed to help :-) I personally have already some skills, but also don't
feel as ebuild/eclass guru :-) hehe

2017-06-05 16:41 GMT+02:00 LGTrader <notifications@github.com>:

**Comment by Alessandro-Barbieri** [comment]
@LGTrader do you have the text of the EULA? Usually is found inside the disc or somewhere installed on the pc.

**Comment by LGTrader** [comment]
[license_agreement.txt](https://github.com/archenroot/gentoo-overlay/files/1052703/license_agreement.txt)

**Comment by Alessandro-Barbieri** [comment]
@LGTrader Thank you very much!
