### ISSUE TITLE
archenroot/tensorflow-9999 digest failure

### ISSUE THREAD

**Issue by LGTrader** [archenroot/gentoo-overlay#20]
This started on 6/2/17. Prior to that tensorflow-9999 installed fine.

```
c2RAID6 ~ # emerge -fDuN @world
Calculating dependencies | * Digest verification failed:
 * /var/lib/layman/archenroot/sci-libs/tensorflow/tensorflow-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2035
 * Expected: 2024
```

Additionally, file permissions for this ebuild were marked executable while 0.5 & 0.6 were not.

**Comment by Alessandro-Barbieri** [comment]
try now, if doesn't work reopen

**Comment by LGTrader** [comment]
All good now. tensorflow-9999 running under Keras in PyCharm all good.

There are a couple of other things but I'll post those as a new report for you to think about in the future.

Thanks!
