### ISSUE TITLE
Build error sci-libs/magma-2.2.0

### ISSUE THREAD

**Issue by storgrim** [archenroot/gentoo-overlay#25]
make -j9 shared 
make: Nothing to be done for 'shared'.
 * ======================  COMPILE PHASE =====================
 * lib/libmagma.so{,.2.2}
mv: missing destination file operand after 'lib/libmagma.so{,.2.2}'
Try 'mv --help' for more information.
>>> Source compiled.
>>> Test phase [not enabled]: sci-libs/magma-2.2.0

>>> Install magma-2.2.0 into /var/tmp/portage/sci-libs/magma-2.2.0/image/ category sci-libs
!!! dolib: lib/libmagma.so does not exist
!!! dolib: lib/libmagma.so.2 does not exist
 * ERROR: sci-libs/magma-2.2.0::archenroot failed (install phase):
 *   dolib failed

seems like the mv command is missing target.

**Comment by archenroot** [comment]
Going to look at this...

**Comment by archenroot** [comment]
Seriously looking into this :-))))

**Comment by archenroot** [comment]
I also noticed few changes, new 2.0.3 version is out and I noticed CMake support:
https://bitbucket.org/icl/magma/src

Might be worth it to migrate the ebuild completely to support Gentoo Cmake eclasses which simplify all work.

**Comment by archenroot** [comment]
@storgrim - could you please confirm that it works now? I compiled with use flag pascal as I am on 1080TI machine now. Thanks for feedback.

I will also update package to latest version 2.3

**Comment by archenroot** [comment]
Please open new issue if any kind of problems occurs as I was able to build.
