### ISSUE TITLE
TensorFlow - put generic Java dependency instead of Oracle Java.

### ISSUE THREAD

**Issue by strelec** [archenroot/gentoo-overlay#32]
This is what you currently depend on:

`	>=dev-java/oracle-jdk-bin-1.8.0.152-r1`

Could you instead depend on generic java and let the user choose the implementation?

Also, arch linux package for TensorFlow does not seem to depend on Java at all.
https://www.archlinux.org/packages/community/x86_64/tensorflow/

**Comment by archenroot** [comment]
I am now more focused to make it properly work with CUDA 9 and CUDNN 7. Leaving completelly cuda 8 behind.

https://github.com/tensorflow/tensorflow/issues/12052
https://gist.github.com/smitshilu/53cf9ff0fd6cdb64cca69a7e2827ed0f

I will check the java dependency if required, but of course you are free to create PR :-)

Note: the result of this work will be merged when stabilized to the Gentoo main tree

**Comment by archenroot** [comment]
In general I think that with introduction of virtual packages as proxies to real packages we can do following:
- make java optional as use flag to build java api
- as dependency only use virtual package for java (virtual/jdk)

**Comment by archenroot** [comment]
@strelec - actually yes, as expected I might be do following:
1. remove it completely as bazel has dependency:
```
* dependency graph for dev-util/bazel-0.7.0
 `--  dev-util/bazel-0.7.0  ~amd64 
   `--  virtual/jdk-1.8.0-r3  (virtual/jdk) amd64 
   `--  app-arch/unzip-6.0_p20  (app-arch/unzip) amd64 
   `--  app-arch/zip-3.0-r3  (app-arch/zip) amd64 
   `--  dev-java/java-config-2.2.0-r3  (>=dev-java/java-config-2.2.0-r3) amd64 
[ dev-util/bazel-0.7.0 stats: packages (5), max depth (1) ]
```
2. I can include explicitelly virtual/jdk on java api build -> need to introduce java use flag
