### ISSUE TITLE
libvisio2svg ebuilds missing dependancies

### ISSUE THREAD

**Issue by geekasylum** [archenroot/gentoo-overlay#40]
Fistly thank you so much for creating ebuilds for this - I was looking for a way to convert VSS files to SVG and I almost fell off my chair when I saw a comment on the yEd forums that you had created gentoo ebuilds for this obscure but vital utility.

To get libvisio2svg to compile on current gentoo I had to add some missing dependencies. Im not a big git user so hopefully this will suffice in place of a pull request.

1) media-libs/libemf2svg has a dependency on libiconv.  The DEPEND= line should be changed as follows, since dev-libs/libiconv blocks sys-libs/glibc, which is bad.
See https://forums.gentoo.org/viewtopic-t-1031360-view-previous.html for more info.

DEPEND="virtual/libiconv
        media-libs/libpng"

2) media-libs/libvisio2svg needs some missing dependencies added. These are provided by gentoo. The DEPEND= line should read as follows:

DEPEND="dev-libs/librevenge
        media-libs/libemf2svg
        media-libs/libvisio
        media-libs/libwmf"

With those two chenges in place, I was able to emerge media-libs/libvisio2svg properly.

Thanks again for the work on this.

**Comment by archenroot** [comment]
@geekasylum - sorry for delay like this, going to look into that.
