### ISSUE TITLE
add burp manifest

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [archenroot/gentoo-overlay#6]
```
Updating metadata cache for the archenroot repository ... 
* Manifest not found for '/var/lib/layman/archenroot/app-backup/burp/burp-1.6.18.ebuild'
Error processing app-backup/burp-1.6.18, continuing...

```

**Comment by Alessandro-Barbieri** [comment]
well ... versions in sourceforge are:
2.1.8
2.0.54
1.4.40
1.3.48

**Comment by archenroot** [comment]
I started looking to version bump and realized that probably Marek Szuba did the work and Gentoo has in its repos latest stable version now for about 1 month.

I migrated it into my repo as well, but just for my purpose, you shoul use the Gentoo one now :-)

**Comment by archenroot** [comment]
I noted in the latest version provided by Gentoo some missing dependency check:
https://packages.gentoo.org/packages/dev-libs/uthash

Where I failed to emerge on:
```
checking for uthash.h... no
configure: error: Cannot find uthash.h, please install uthash

!!! Please attach the following file when seeking support:
!!! /tmp/portage/app-backup/burp-2.0.54/work/burp-2.0.54/config.log
 * ERROR: app-backup/burp-2.0.54::archenroot failed (configure phase):
 *   econf failed
 * 
 * Call stack:
 *               ebuild.sh, line  115:  Called src_configure
 *             environment, line 3328:  Called econf '--localstatedir=/var' '--sysconfdir=/etc/burp' '--enable-largefile' '--enable-acl' '--enable-ipv6' '--enable-xattr'
 *        phase-helpers.sh, line  665:  Called __helpers_die 'econf failed'
 *   isolated-functions.sh, line  117:  Called die
 * The specific snippet of code:
 *   		die "$@"

```

Later there is missing librsync as well, so need to manually emerge.

I raised finally a bug with Gentoo as I am not able to support this package:
https://bugs.gentoo.org/show_bug.cgi?id=617984

as I would like to remove obsolete versions from overlay tree completely.

**Comment by archenroot** [comment]
Closing as maintained in Gentoo tree.
https://packages.gentoo.org/packages/app-backup/burp
