### ISSUE TITLE
cudnn-8.0-linux-x64-v5.1.tgz checksum failure

### ISSUE THREAD

**Issue by nexusdk** [archenroot/gentoo-overlay#7]
ebuild sh256 is a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8
File download sha256 is c10719b36f2dd6e9ddc63e3189affaa1a94d7d027e63b71c3f64d449ab0645ce

I downloaded the file twice, got the same sha256.

**Comment by archenroot** [comment]
Hm, I checked the file on my laptop:
ares archenroot # sha256sum /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz 
a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8  /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz

Additionally the output:
ares archenroot # ls -la /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz
-rw-rw-r-- 1 portage portage 100504805 Dec  2 21:23 /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz

**Comment by archenroot** [comment]
Can you provide download link?

**Comment by nexusdk** [comment]
Here is the file I have:
ftp://ftp.cs.up.ac.za/cudnn-8.0-linux-x64-v5.1.tgz

**Comment by archenroot** [comment]
I cannot download the file. Anyway I downloaded again file from official Nvidia site at:
https://developer.nvidia.com/rdp/cudnn-download

Now I checked newly downloaded file against the one I have in /usr/portage/distfiles:
```
ares ~ # sha256sum /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz 
a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8  /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz
ares ~ # ls -la /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz 
-rw-rw-r-- 1 portage portage 100504805 Dec  2 21:23 /usr/portage/distfiles/cudnn-8.0-linux-x64-v5.1.tgz

```

Now newly downloaded file:
```
zangetsu@ares ~/Downloads $ sha256sum cudnn-8.0-linux-x64-v5.1.tgz 
c10719b36f2dd6e9ddc63e3189affaa1a94d7d027e63b71c3f64d449ab0645ce  cudnn-8.0-linux-x64-v5.1.tgz
zangetsu@ares ~/Downloads $ ls -la cudnn-8.0-linux-x64-v5.1.tgz 
-rw-r--r-- 1 zangetsu users 103174002 11. May 13.54 cudnn-8.0-linux-x64-v5.1.tgz
```

So, either they replaced the file with some other version during time and I won't be surprised as I was able to build... or I had corrupted download file, but in that case I expect not being able to compile as some files are missing...

Anyway I replaced obsolete file with latest available from Nvidia which has same sha256sum string as yours and now it should work, I emerged with result:
```
>>> Completed installing nvidia-cuda-cudnn-8.0 into /tmp/portage/dev-libs/nvidia-cuda-cudnn-8.0/image/

 * Final size of build directory: 151008 KiB
 * Final size of installed tree: 151008 KiB



 * QA Notice: Pre-stripped files found:
 * /usr/lib64/libcudnn.so.5.1.10
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   usr/lib64/libcudnn_static.a

>>> Installing (1 of 1) dev-libs/nvidia-cuda-cudnn-8.0::archenroot

>>> Recording dev-libs/nvidia-cuda-cudnn in "world" favorites file...
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: config file '/etc/modprobe.d/bbswitch.conf' needs updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.

 * IMPORTANT: 22 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

ares nvidia-cuda-cudnn # 
```

Let me know if all ok now.

Regarding th QA Notice this is related to strip by upstream:

> Note: Some packages unfortunately handle stripping by themselves, inside the upstream provided makefiles. This is an error and should be reported. All packages should leave Portage the task of the stripping or simply restrict stripping entirely. The main exception to this are binary packages. They are usually stripped by upstream, outside of Portage control.

**Comment by archenroot** [comment]
Closing as fixed now.
